### ISSUE TITLE
Not work with 13.4.1

### ISSUE THREAD

**Issue by marianled** [ITenthusiasm/svelte-kit-supertokens#1]
Hello,

Thank you for providing the project.
it runs great with the version supertokens-nodes 12.6.x
version 13.4.1 is currently available.
Unfortunately, the transfer values no longer work correctly.

**Comment by ITenthusiasm** [comment]
Thanks for opening this! I'll try to take a look sometime this weekend.

**Comment by ITenthusiasm** [comment]
Hey @marianled, the SuperTokens team said that they'll be releasing some new code soon that will allow me to fix this issue in a cleaner way. [I was encouraged to wait](https://discord.com/channels/603466164219281420/1049748644837990451/1096052219473830000) until the new code was released before addressing this. So I'm sure the update will come soon. As soon as the update comes, I'll address this issue. Thanks again!

**Comment by marianled** [comment]
Thanks.
That sounds good.  i will be happy to wait

**Comment by marianled** [comment]
Hello, version 14.1.1 was released a few days ago.

**Comment by ITenthusiasm** [comment]
@marianled Awesome! Thanks for letting me know! I'm surprised I didn't see an announcement in Discord yet. I'll try to take a look soon. Sometime between this weekend and next Friday, likely.

**Comment by ITenthusiasm** [comment]
@marianled Just keeping you posted. I have started looking into this. Don't know if I have an explicit timeline (because it's hard to predict what life brings), but I'd say the changes are probably about 50-75% done.

**Comment by marianled** [comment]
Don't panic. I'm very glad you took up the topic.

**Comment by ITenthusiasm** [comment]
@marianled I think this should be resolved now. You can check out the latest version of `main` to verify. If there are still any problems, feel free to re-open this issue.

Please note that the application has been updated to work with `supertokens-node@14` (the latest version of the package), not `supertokens-node@13`.

**Comment by marianled** [comment]
Hi,

It looks great, I will test it extensively, but everything seems to work.

Thank you very much for your efforts

**Comment by ITenthusiasm** [comment]
For sure! Happy to help 🙏🏾
